BBPATH .= ":${LAYERDIR}"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "meta-immersive"
BBFILE_PATTERN_meta-immersive = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-immersive = "10"

LAYERDEPENDS_meta-immersive = "core raspberrypi"
LAYERSERIES_COMPAT_meta-immersive = "scarthgap styhead"
