"""netmanager.py — DHCP on the control node, driven by the room-model.

The control node owns the dedicated switch's network. Each node's identity in
the room-model carries net.mac and net.ip; this module turns those into dnsmasq
DHCP reservations (MAC -> fixed IP + hostname) plus a small dynamic pool that
hands temporary leases to nodes that have not been enrolled yet. Setting an IP
on the website therefore *takes effect*: regenerate the config, reload dnsmasq,
and that node gets that address on its next lease.

The config generation is pure and unit-tested; writing the file and reloading
the daemon is guarded so this imports and runs off-target.

room-model "network" block (defaults applied if absent):
  { "iface": "eth0", "subnet": "10.0.0.0/24", "gateway": "10.0.0.13",
    "dns": "10.0.0.13", "pool_start": "10.0.0.200", "pool_end": "10.0.0.250",
    "lease": "12h" }
"""

from __future__ import annotations

import subprocess
from pathlib import Path

DEFAULT_NETWORK = {
    "iface": "eth0",
    "subnet": "10.0.0.0/24",
    "gateway": "10.0.0.13",
    "dns": "10.0.0.13",
    "pool_start": "10.0.0.200",
    "pool_end": "10.0.0.250",
    "lease": "12h",
}

DEFAULT_CONF_PATH = "/etc/dnsmasq.d/immersive.conf"


def reservations(room_model: dict):
    """(mac, ip, hostname) for every node that has both a MAC and an IP."""
    out = []
    for n in room_model.get("nodes", []):
        net = n.get("net", {})
        mac, ip = net.get("mac"), net.get("ip")
        if mac and ip:
            out.append((mac.lower(), ip, n["node"]))
    return out


def generate_conf(room_model: dict, network: dict = None) -> str:
    """Render the dnsmasq fragment for the immersive network."""
    net = {**DEFAULT_NETWORK, **(network or {})}
    lines = [
        "# Generated by immersive netmanager — do not edit by hand.",
        f"interface={net['iface']}",
        "bind-interfaces",
        "dhcp-authoritative",
        # dynamic pool for not-yet-enrolled nodes
        f"dhcp-range={net['pool_start']},{net['pool_end']},{net['lease']}",
    ]
    if net.get("gateway"):
        lines.append(f"dhcp-option=3,{net['gateway']}")     # router
    if net.get("dns"):
        lines.append(f"dhcp-option=6,{net['dns']}")         # dns
    lines.append("")
    lines.append("# Per-node reservations (MAC -> fixed IP) from the room-model")
    for mac, ip, host in reservations(room_model):
        lines.append(f"dhcp-host={mac},{ip},{host}")
    return "\n".join(lines) + "\n"


class NetManager:
    def __init__(self, conf_path: str = DEFAULT_CONF_PATH,
                 reload_cmd=("systemctl", "reload-or-restart", "dnsmasq")):
        self.conf_path = Path(conf_path)
        self.reload_cmd = list(reload_cmd)
        self.enabled = True

    def apply(self, room_model: dict, network: dict = None) -> bool:
        """Write the reservations and reload dnsmasq. Returns True if reloaded.
        No-ops cleanly where dnsmasq / the conf dir is absent (dev box)."""
        if not self.enabled:
            return False
        conf = generate_conf(room_model, network)
        try:
            self.conf_path.parent.mkdir(parents=True, exist_ok=True)
            self.conf_path.write_text(conf)
        except (PermissionError, OSError) as e:
            print(f"[net] cannot write {self.conf_path}: {e}")
            return False
        try:
            subprocess.run(self.reload_cmd, check=True, capture_output=True)
            print(f"[net] dnsmasq reloaded ({len(reservations(room_model))} reservations)")
            return True
        except FileNotFoundError:
            print("[net] dnsmasq/systemctl not present; wrote conf only (dev box)")
        except subprocess.CalledProcessError as e:
            print(f"[net] dnsmasq reload failed: {e.stderr.decode().strip()}")
        return False


if __name__ == "__main__":
    import json, sys
    model = json.load(open(sys.argv[1] if len(sys.argv) > 1 else "room-model.json"))
    print(generate_conf(model, model.get("network")))
